//! Auto-generated by `datalink_shim_sqlite_dynlink_emit::emit_dynlink`
//! (Phase A, opaque-blob scalar dispatch). Do NOT edit by hand — regenerate.
#![allow(unused_imports, dead_code)]
#![allow(unsafe_op_in_unsafe_fn)]

mod bindings {
    wit_bindgen::generate!({
        path: "wit",
        world: "bridge",
        generate_all,
    });
}

use bindings::exports::sqlite::extension::metadata::{
    Guest as MetadataGuest, Manifest, ScalarFunctionSpec,
};
use bindings::exports::sqlite::extension::scalar_function::Guest as ScalarFunctionGuest;
use bindings::sqlite::extension::types::{FunctionFlags, SqlValue};

use bindings::compose::dynlink::linker;

const PROVIDER_ID: &str = "timescale_core-composed";
const EXTENSION_ROOT: &str = "timescale";
const CATALOG_EXTENSION: &str = "timescaledb";
const CATALOG_VERSION: &str = "2.19.0";

fn resolve() -> Result<linker::Instance, String> {
    linker::resolve_by_id(&PROVIDER_ID.to_string())
        .map_err(|e| format!("dynlink resolve('{}'): {:?}", PROVIDER_ID, e))
}

// -----------------------------------------------------------
// CBOR envelope (mirrors provider crate's Request/Response).
// -----------------------------------------------------------

#[derive(Debug, Clone)]
enum CborValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<CborValue>),
}

impl serde::Serialize for CborValue {
    fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
        match self {
            CborValue::Null => s.serialize_unit(),
            CborValue::Bool(b) => s.serialize_bool(*b),
            CborValue::Int(i) => s.serialize_i64(*i),
            CborValue::Float(f) => s.serialize_f64(*f),
            CborValue::Text(t) => s.serialize_str(t),
            CborValue::Bytes(b) => s.serialize_bytes(b),
            CborValue::List(items) => {
                use serde::ser::SerializeSeq;
                let mut seq = s.serialize_seq(Some(items.len()))?;
                for item in items {
                    seq.serialize_element(item)?;
                }
                seq.end()
            }
        }
    }
}

#[derive(Debug, Clone, serde::Serialize)]
struct Request {
    #[serde(rename = "v")]
    version: u32,
    args: Vec<CborValue>,
}

#[derive(Debug, Clone, serde::Deserialize)]
struct Response {
    #[serde(default)]
    ok: Option<ResponseValue>,
    #[serde(default)]
    err: Option<String>,
}

#[derive(Debug, Clone)]
enum ResponseValue {
    Null,
    Bool(bool),
    Int(i64),
    Float(f64),
    Text(String),
    Bytes(Vec<u8>),
    List(Vec<ResponseValue>),
}

impl<'de> serde::Deserialize<'de> for ResponseValue {
    fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
        use serde::de::{Error, MapAccess, SeqAccess, Visitor};
        struct V;
        impl<'de> Visitor<'de> for V {
            type Value = ResponseValue;
            fn expecting(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
                f.write_str("a CBOR value (null, bool, int, float, text, bytes, list)")
            }
            fn visit_unit<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_none<E: Error>(self) -> Result<ResponseValue, E> { Ok(ResponseValue::Null) }
            fn visit_bool<E: Error>(self, v: bool) -> Result<ResponseValue, E> { Ok(ResponseValue::Bool(v)) }
            fn visit_i64<E: Error>(self, v: i64) -> Result<ResponseValue, E> { Ok(ResponseValue::Int(v)) }
            fn visit_u64<E: Error>(self, v: u64) -> Result<ResponseValue, E> {
                if v <= i64::MAX as u64 { Ok(ResponseValue::Int(v as i64)) }
                else { Err(E::custom("u64 overflow to i64")) }
            }
            fn visit_f64<E: Error>(self, v: f64) -> Result<ResponseValue, E> { Ok(ResponseValue::Float(v)) }
            fn visit_str<E: Error>(self, v: &str) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v.to_string())) }
            fn visit_string<E: Error>(self, v: String) -> Result<ResponseValue, E> { Ok(ResponseValue::Text(v)) }
            fn visit_bytes<E: Error>(self, v: &[u8]) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v.to_vec())) }
            fn visit_byte_buf<E: Error>(self, v: Vec<u8>) -> Result<ResponseValue, E> { Ok(ResponseValue::Bytes(v)) }
            fn visit_seq<A: SeqAccess<'de>>(self, mut s: A) -> Result<ResponseValue, A::Error> {
                let mut items = Vec::new();
                while let Some(v) = s.next_element::<ResponseValue>()? { items.push(v); }
                Ok(ResponseValue::List(items))
            }
            fn visit_map<A: MapAccess<'de>>(self, mut m: A) -> Result<ResponseValue, A::Error> {
                let k: Option<String> = m.next_key()?;
                let k = k.ok_or_else(|| A::Error::custom("empty map"))?;
                let v = match k.as_str() {
                    "Null" => { let _: serde::de::IgnoredAny = m.next_value()?; ResponseValue::Null }
                    "Bool" => ResponseValue::Bool(m.next_value()?),
                    "Int"  => ResponseValue::Int(m.next_value()?),
                    "Float" => ResponseValue::Float(m.next_value()?),
                    "Text" => ResponseValue::Text(m.next_value()?),
                    "Bytes" => {
                        let b: serde_bytes::ByteBuf = m.next_value()?;
                        ResponseValue::Bytes(b.into_vec())
                    }
                    "List" => ResponseValue::List(m.next_value()?),
                    other => return Err(A::Error::custom(format!("unknown tag: {}", other))),
                };
                Ok(v)
            }
        }
        d.deserialize_any(V)
    }
}

fn encode_request(args: Vec<CborValue>) -> Result<Vec<u8>, String> {
    let mut out = Vec::new();
    ciborium::into_writer(&Request { version: 1, args }, &mut out)
        .map_err(|e| format!("cbor encode: {}", e))?;
    Ok(out)
}

fn decode_response(bytes: &[u8]) -> Result<Response, String> {
    ciborium::from_reader(bytes).map_err(|e| format!("cbor decode: {}", e))
}

fn call(method: &str, args: Vec<CborValue>) -> Result<ResponseValue, String> {
    let inst = resolve()?;
    let payload = encode_request(args)?;
    let bytes = inst
        .invoke(&method.to_string(), &payload)
        .map_err(|e| format!("{}: invoke: {:?}", method, e))?;
    let resp = decode_response(&bytes)?;
    if let Some(err) = resp.err {
        return Err(format!("{}: {}", method, err));
    }
    Ok(resp.ok.unwrap_or(ResponseValue::Null))
}

// -----------------------------------------------------------
// SqlValue marshalling — variant discipline per the @1.0.0
// contract. The `wit-value` arm is Phase-A-out-of-scope; the
// bridge treats it as null in both directions.
// -----------------------------------------------------------

fn sqlv_to_cbor(v: &SqlValue) -> Result<CborValue, String> {
    Ok(match v {
        SqlValue::Null => CborValue::Null,
        SqlValue::Integer(i) => CborValue::Int(*i),
        SqlValue::Real(f) => CborValue::Float(*f),
        SqlValue::Text(t) => CborValue::Text(t.clone()),
        SqlValue::Blob(b) => CborValue::Bytes(b.clone()),
        // WitValue is Phase-A-out-of-scope. Prior code silently
        // downgraded it to CBOR null, which lied to the provider
        // (an explicit-typed argument became indistinguishable
        // from a real NULL). Surface an explicit error instead so
        // callers see a diagnostic on the SQL side.
        SqlValue::WitValue(_) => {
            return Err("bridge: WitValue arg not supported in dynlink Phase A".to_string());
        }
    })
}

fn response_to_sqlv(v: ResponseValue) -> Result<SqlValue, String> {
    Ok(match v {
        ResponseValue::Null => SqlValue::Null,
        ResponseValue::Bool(b) => SqlValue::Integer(if b { 1 } else { 0 }),
        ResponseValue::Int(i) => SqlValue::Integer(i),
        ResponseValue::Float(f) => SqlValue::Real(f),
        ResponseValue::Text(t) => SqlValue::Text(t),
        ResponseValue::Bytes(b) => SqlValue::Blob(b),
        // A list-shaped response has no SQLite scalar sqlvalue
        // arm. Prior code silently returned SqlValue::Null, hiding
        // a shape mismatch behind an implicit NULL. Return an
        // explicit error so the SQL side sees a diagnostic.
        ResponseValue::List(_) => {
            return Err("bridge: list-shaped response not supported".to_string());
        }
    })
}

fn scalar_name_by_id(id: u64) -> Option<&'static str> {
    match id {
        _ => None,
    }
}

/// SQL-name aliasing: translate a compact-form SQL name (e.g.
/// `st_geomfromtext`) to its WIT-canonical (long) form
/// (`st_geom_from_text`) before kebab-casing to the provider
/// method name. The catalog carries both spellings as scalars in
/// `leaf.scalars` (both are advertised via `metadata.describe()`
/// so callers can use either), and as first-class `[[aliases]]`
/// entries. The provider dispatch only matches the WIT-canonical
/// form; the bridge's per-row `call` calls `canonical_for(name)`
/// so both spellings route to the same provider arm.
fn canonical_for(name: &str) -> &str {
    match name {
        other => other,
    }
}

// -----------------------------------------------------------
// Guest impls.
// -----------------------------------------------------------

struct Component;

impl MetadataGuest for Component {
    fn describe() -> Manifest {
        let scalar_functions: Vec<ScalarFunctionSpec> = vec![
        ];
        Manifest {
            name: EXTENSION_ROOT.to_string(),
            version: CATALOG_VERSION.to_string(),
            scalar_functions,
            aggregate_functions: vec![],
            collations: vec![],
            vtabs: vec![],
            dot_commands: vec![],
            has_authorizer: false,
            has_update_hook: false,
            has_commit_hook: false,
            has_wal_hook: false,
            wal_hook_id: 0,
            declared_capabilities: vec![],
            optional_capabilities: vec![],
            preferred_prefix: None,
            prefix_expansion: None,
            typed_values: vec![],
        }
    }
}

impl ScalarFunctionGuest for Component {
    fn call(func_id: u64, args: Vec<SqlValue>) -> Result<SqlValue, String> {
        let name = scalar_name_by_id(func_id)
            .ok_or_else(|| format!("unknown function id {}", func_id))?;
        // SQL-style null propagation. Providers that need to
        // observe explicit NULL arguments will need a follow-up
        // Phase to opt in per-arm.
        if args.iter().any(|v| matches!(v, SqlValue::Null)) {
            return Ok(SqlValue::Null);
        }
        // Alias translation: SQL name → WIT-canonical → provider
        // method (kebab-case). Compact-form SQL names (e.g.
        // `st_geomfromtext`) route through `canonical_for` to their
        // long form (`st_geom_from_text`) before kebab-casing;
        // non-alias names pass through unchanged. See
        // `canonical_for` above.
        let canonical = canonical_for(name);
        let method = canonical.replace('_', "-");
        let cbor_args: Vec<CborValue> = args
            .iter()
            .map(sqlv_to_cbor)
            .collect::<Result<Vec<_>, String>>()?;
        let resp = call(&method, cbor_args)?;
        response_to_sqlv(resp)
    }
}

bindings::export!(Component with_types_in bindings);
